---
---
title: "JK"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###INSTALL PACKAGES
```{r}
#install.packages("openintro")
```


###LOAD PACKAGES
```{r}
library(dplyr)
library(tidyverse)
library(lubridate)
library(openintro)
library(usmap)
library(gridExtra)
```

###CLEAN MEDIA DATA
```{r}
### CLEANING MEDIA DATA
#Read the media data
media <- read.csv("suicid-or-suicid-and-sampled-stories-20181213194457.csv")
media2 <- read.csv("suicid-or-suicid-and-stories-over-time-20181213191601.csv")

#Extract the year information from the publication date
media <- media %>% mutate(date = ymd_hms(publish_date))
media <- media %>% separate(date, c("date", "hour_min"), " ")
media <- media %>% mutate(year = year(date), month = month(date), day = day(date))
media <- media %>% filter(language == "en")

#Separate the publication state (state, year) into 2 separate variables: state and country
media <- media %>% separate(media_pub_state, c("state", "country"), ",")

#Create a variable with state abbreviations from the state name
media <- media %>% mutate(state_abb = ifelse(nchar(state)>2, state.abb[match(state, state.name)], state))

#Find titles that include the term 'suicid' and create a new variable "suicide_title"" that returns 1 if "suicid" is present, else 0
media <- media %>% mutate(suicide_title = ifelse(str_detect(title, "suicid"), 1, 0))
```


###COUNT AND RATIO PLOTS
```{r}
###COUNT AND RATIO PLOTS
#Count plot
p1 <- media2 %>% 
  ggplot(aes(date, count, group = 1)) + 
  geom_line(colour = "darkorchid4") + 
  scale_x_discrete(breaks = c("2011-01-01", "2012-01-01", "2013-01-01", "2014-01-01", "2015-01-01", "2016-01-01", "2017-01-01", "2018-01-01"), labels = c("2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018")) + 
  xlab("Year") + ylab("Count")

print(p1)

#Ratio plot
p2 <- media2 %>% 
  ggplot(aes(date, ratio, group = 1)) + 
  geom_line(colour = "darkorchid4") + 
  scale_x_discrete(breaks = c("2011-01-01", "2012-01-01", "2013-01-01", "2014-01-01", "2015-01-01", "2016-01-01", "2017-01-01", "2018-01-01"), labels = c("2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018")) + 
  xlab("Year") + ylab("Ratio")

print(p2)
```


###USMAP PLOTS FOR MEDIA
```{r}
###`usmap` plots
#Create data for 2011 
map_2011 <- media %>% 
  group_by(state_abb) %>% 
  filter (year == "2011") %>% 
  summarize(num_title = n()) %>%
  rename(state = state_abb)
#Format the data
map_2011 <- map_2011[!(map_2011$state == ""),]
map_2011 <- map_2011[!is.na(map_2011$state),]
#Plot
p_2011 <- plot_usmap(data = as.data.frame(map_2011), values = "num_title") + 
  scale_fill_gradientn(limits = c(0,700), colours=c("yellow", "darkorange1", "red3", "violetred1", "maroon3", "maroon4", "purple4"), name = "# of Stories") +
  theme(legend.position="none")


#Create data for 2012 
map_2012 <- media %>% 
  group_by(state_abb) %>% 
  filter (year == "2012") %>% 
  summarize(num_title = n()) %>%
  rename(state = state_abb)
#Format the data
map_2012 <- map_2012[!(map_2012$state == ""),]
map_2012 <- map_2012[!is.na(map_2012$state),]
#Plot
p_2012 <- plot_usmap(data = as.data.frame(map_2012), values = "num_title") + 
  scale_fill_gradientn(limits = c(0,700), colours=c("yellow", "darkorange1", "red3", "violetred1", "maroon3", "maroon4", "purple4"), name = "# of Stories") +
  theme(legend.position="none")


#Create data for 2013 
map_2013 <- media %>% 
  group_by(state_abb) %>% 
  filter (year == "2013") %>% 
  summarize(num_title = n()) %>%
  rename(state = state_abb)
#Format the data
map_2013 <- map_2013[!(map_2013$state == ""),]
map_2013 <- map_2013[!is.na(map_2013$state),]
#Plot
p_2013 <- plot_usmap(data = as.data.frame(map_2013), values = "num_title") + 
  scale_fill_gradientn(limits = c(0,700), colours=c("yellow", "darkorange1", "red3", "violetred1", "maroon3", "maroon4", "purple4"), name = "# of Stories") +
  theme(legend.position="none")


#Create data for 2014 
map_2014 <- media %>% 
  group_by(state_abb) %>% 
  filter (year == "2014") %>% 
  summarize(num_title = n()) %>%
  rename(state = state_abb)
#Format the data
map_2014 <- map_2014[!(map_2014$state == ""),]
map_2014 <- map_2014[!is.na(map_2014$state),]
#Plot
p_2014 <- plot_usmap(data = as.data.frame(map_2014), values = "num_title") + 
  scale_fill_gradientn(limits = c(0,700), colours=c("yellow", "darkorange1", "red3", "violetred1", "maroon3", "maroon4", "purple4"), name = "# of Stories") +
  theme(legend.position="none")


#Create data for 2015 
map_2015 <- media %>% 
  group_by(state_abb) %>% 
  filter (year == "2015") %>% 
  summarize(num_title = n()) %>%
  rename(state = state_abb)
#Format the data
map_2015 <- map_2015[!(map_2015$state == ""),]
map_2015 <- map_2015[!is.na(map_2015$state),]
#Plot
p_2015 <- plot_usmap(data = as.data.frame(map_2015), values = "num_title") + 
  scale_fill_gradientn(limits = c(0,700), colours=c("yellow", "darkorange1", "red3", "violetred1", "maroon3", "maroon4", "purple4"), name = "# of Stories") +
  theme(legend.position="none")


#Create data for 2016 
map_2016 <- media %>% 
  group_by(state_abb) %>% 
  filter (year == "2016") %>% 
  summarize(num_title = n()) %>%
  rename(state = state_abb)
#Format the data
map_2016 <- map_2016[!(map_2016$state == ""),]
map_2016 <- map_2016[!is.na(map_2016$state),]
#Plot
p_2016 <- plot_usmap(data = as.data.frame(map_2016), values = "num_title") + 
  scale_fill_gradientn(limits = c(0,700), colours=c("yellow", "darkorange1", "red3", "violetred1", "maroon3", "maroon4", "purple4"), name = "# of Stories")  +
  theme(legend.position="none")


#Create data for 2017 
map_2017 <- media %>% 
  group_by(state_abb) %>% 
  filter (year == "2017") %>% 
  summarize(num_title = n()) %>%
  rename(state = state_abb)
#Format the data
map_2017 <- map_2017[!(map_2017$state == ""),]
map_2017 <- map_2017[!is.na(map_2017$state),]
#Plot
p_2017 <- plot_usmap(data = as.data.frame(map_2017), values = "num_title") + 
  scale_fill_gradientn(limits = c(0,700), colours=c("yellow", "darkorange1", "red3", "violetred1", "maroon3", "maroon4", "purple4"), name = "# of Stories") +
  theme(legend.position="none")


#Create data for 2018 
map_2018 <- media %>% 
  group_by(state_abb) %>% 
  filter (year == "2018") %>% 
  summarize(num_title = n()) %>%
  rename(state = state_abb)
#Format the data
map_2018 <- map_2018[!(map_2018$state == ""),]
map_2018 <- map_2018[!is.na(map_2018$state),]
#Plot
p_2018 <- plot_usmap(data = as.data.frame(map_2018), values = "num_title") + 
  scale_fill_gradientn(limits = c(0,700), colours=c("yellow", "darkorange1", "red3", "violetred1", "maroon3", "maroon4", "purple4"), name = "# of Stories") +
  theme(legend.position = "right")

grid.arrange(p_2011, p_2012, p_2013, p_2014, p_2015, p_2016, p_2017, p_2018, nrow = 4)
```


###TOP10 MEDIA & SUICIDE PLOTS
```{r}
###PLOT OF TOP MEDIA SOURCES REPORTING ON SUICIDE
#Top 10 media sources with articles on suicide
top_media <- media %>% 
  group_by(media_name) %>%
  summarize(total = n())%>%
  arrange(desc(total))

p_top_media <- ggplot(data = subset(top_media, total %in% total[1:10]), aes(media_name, total, group = 1)) + 
  geom_bar(stat = "identity") + 
  coord_flip() + 
  xlab("Media Name") + ylab("Number of Articles") + 
  ggtitle("Top 10: Media Sources with Articles on Suicide (2011-2018)")
print(p_top_media)

#Top 10 media sources with suicide in the article title
top_suicide <- media %>%
  group_by(media_name) %>% 
  summarize(total = sum(suicide_title)) %>%
  arrange(desc(total))

p_top_suicide <- ggplot(data = subset(top_suicide, total %in% total[1:10]), aes(media_name, total, group = 1)) + 
  geom_bar(stat = "identity") + 
  coord_flip() + 
  xlab("Media Name") + ylab("Number of Articles") + 
  ggtitle("Top 10: Media Sources with 'Suicide' in the Article Titles (2011-2018)")
print(p_top_suicide)
```


###COMBINE CDC WITH MEDIA
```{r}
###CDC###
#Crude rate is the number of deaths per state population per 1 million people
cdc <- read.csv("cdc_statesuicide_1999_2016.csv")
cdc_join <- cdc %>% mutate(year = as.factor(year)) %>%
  group_by(year, state) %>%
  summarise(deaths = sum(death), populations = sum(population), rate_pmil = (deaths/populations)*1000000)
cdc_join <- cdc_join %>% 
  mutate(state_abb = ifelse(state == "District of Columbia", "DC", state.abb[match(state, state.name)])) %>%
  filter(year %in% c("2011", "2012", "2013", "2014", "2015", "2016")) %>%
  select(year, state_abb, deaths, populations, rate_pmil) 

media_join <- media %>% mutate(year = as.factor(year)) %>%
  group_by(year, state_abb) %>%
  filter(year %in% c("2011", "2012", "2013", "2014", "2015", "2016")) %>%
  summarize(articles = length(title))
media_join <- media_join[!(media_join$state_abb == ""),]
media_join <- media_join[!is.na(media_join$state_abb),]

#Join
full <- full_join(cdc_join, media_join)
```


###COMBINED ANALYSIS
```{r}
combined_plot <- function(x) {
  full %>% 
  filter(state_abb == x) %>% 
  ggplot(aes(x = year)) + 
  geom_smooth(aes(y = rate_pmil, group = 1, colour = "Sucide Death Rate")) + 
  geom_smooth(aes(y = articles/2, group = 1, colour = "Number of Articles")) + 
  scale_y_continuous(sec.axis = sec_axis(~.*2, name = "Number of Articles on Suicide")) +
  scale_colour_manual(values = c("blue", "red")) + 
  xlab("Year") + ylab("Suicide Death Rate per million people") + ggtitle("California")}

#Example
combined_plot("IL")
```