---
title: "News_data"
author: "Amita Ketkar"
date: "12/13/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("dplyr")
# install.packages("tidyverse")
# install.packages("ggplot2")
# install.packages("Himsc")
library(dplyr)
library(tidyverse)
library(ggplot2)
library(Hmisc)
```

## Add the data 
```{r}
# Set the directory to folder
(setwd(getwd()))
# Read the csv file with raw data
media <- read.csv("suicid-or-suicid-and-sampled-stories-20181213194457.csv")
media2 <- read.csv("suicid-or-suicid-and-stories-over-time-20181213191601.csv")
```
## Clean the data 
```{r}
### CLEANING MEDIA DATA
#Extract the year information from the publication date
media <- media %>% mutate(date = ymd_hms(publish_date))
#Extract the year information from the publication date
media <- media %>% mutate(date = ymd_hms(publish_date))
media <- media %>% separate(date, c("date", "hour_min"), " ")
#>>>>>>> e1a9e0cc6dc4e8cdda100266511b483da5675fe8
media <- media %>% mutate(year = year(date), month = month(date), day = day(date))
media <- media %>% filter(language == "en")
#Separate the publication state (state, year) into 2 separate variables: state and country
media <- media %>% separate(media_pub_state, c("state", "country"), ",")
#Create a variable with state abbreviations from the state name
media <- media %>% mutate(state_abb = ifelse(nchar(state)>2, state.abb[match(state, state.name)], state))
```

##Plot the data :

```{r}
str(media)
# Trend in number od stories covered in a particular year 
media %>% 
  ggplot(aes(year))+
  geom_histogram( binwidth = 0.99, color= "black")

media <-media %>% mutate(id = 1:nrow(media))

media <- media %>% mutate_if(is.character, as.factor)

# Number of stories stratified by the states in a particular year 

media %>% filter(year == 2011) %>% 
  plot_usmap(regions = "state",data = ., values ="stories_id",theme = theme_map())+
  scale_fill_continuous_tableau()+
  theme(legend.position = "right")+
  ggtitle("Stories published across different states in 2011")

media %>% filter(year == 2012) %>% 
  plot_usmap(regions = "state",data = ., values ="stories_id",theme = theme_map())+
  scale_fill_continuous_tableau()+
  theme(legend.position = "right")+
  ggtitle("Stories published across different states in 2012")

media %>% filter(year == 2013) %>% 
  plot_usmap(regions = "state",data = ., values ="stories_id",theme = theme_map())+
  scale_fill_continuous_tableau()+
  theme(legend.position = "right")+
  ggtitle("Stories published across different states in 2013")

media %>% filter(year == 2014) %>% 
  plot_usmap(regions = "state",data = ., values ="stories_id",theme = theme_map())+
  scale_fill_continuous_tableau()+
  theme(legend.position = "right")+
  ggtitle("Stories published across different states in 2014")

media %>% filter(year == 2015) %>% 
  plot_usmap(regions = "state",data = ., values ="stories_id",theme = theme_map())+
  scale_fill_continuous_tableau()+
  theme(legend.position = "right")+
  ggtitle("Stories published across different states in 2015")

media %>% filter(year == 2018) %>% 
  plot_usmap(regions = "state",data = ., values ="stories_id",theme = theme_map())+
  scale_fill_continuous_tableau()+
  theme(legend.position = "right")+
  ggtitle("Stories published across different states in 2016")

```
